# COLORS
GRAY_COLOR = '#626873'
PINK_GRAY_COLOR = '#E3D5E3'
LIGHT_BLUE_DARK = '#D5E9F0'
BLACK = '#222222'
WITHE = '#DDDDDD'
WITHE2 = '#FFFFFF'
LIGHT_GRAY_COLOR = '#B7B6B8'
BG_COLOR = '#F0EBEB'  # background color
PINK_COLOR = '#F5C6F5'
BORDER_COLOR = BLACK
BG_HEADER_COLOR = '#A6DDF5'

# FONTS
FAMILY_FONT = 'roboto'

TYPE_ANALYSIS = ['Select Type of Analysis', 'Data Smoothing', 'PSD Analysis', 'Spectogram Analysis', 'Coherence Analysis', 'Multiple PSD Analysis']
TYPE_FILES = ['Spike - Matlab', 'LFP - Matlab', 'Spike - CSV', 'LFP - CSV']

# SIZES
WIDTH_LEFT_SIDE = 300
WIDTH_RIGHT_SIDE = 300
WIDTH_POPUP = 500
HEIGHT_POPUP = 400
RB_WIDTH = 25
RB_HEIGHT = 25
TITLE_SIZE = 30
SUBTITLE_SIZE = 20
TEXT_SIZE = 12
INPUT_HEIGHT = 30
INPUT_WIDTH = 290
INPUT_WIDTH_CHECK = 20
INPUT_HEIGHT_CHECK = 20
WIDTH_FRAME_PLOT = 700
HEIGHT_FRAME_PLOT = 650

# EXTRAS
BORDER_WIDTH_FRAME = 2
PADY_INPUTS = 5
PADX_INPUTS = 5
PADY_BUTTON = 10
PADX_BUTTON = 50
PADY_SUBTITLE = 10
PADX_SUBTITLE = 60
PADY_LABELS = 5

# TYPE FILE
LFP = 'LFP'
LFP_INT = 0
SPIKE = 'Spike'
SPIKE_INT = 1

CURRENT_FILE = 0
ALL_FILES = 1
ALL = 'All'

# INPUT TYPE
CHECKBOX = 0
COMBOBOX = 1
RADIOBUTTON = 2
TEXTBOX = 3
ENTRY = 4
POPUP = 5
POPUP_MULTIPLE = 6
ENTRY_RANGE = 7

#PATH
MATLAB_SCRIPTS_PATH = '../matlab_scripts/'
FOLDER_RES = './Data/'

#ANALYSIS NAMES
NAME_PSD = 'PSD Analysis'
NAME_SPECTOGRAM = 'Spectogram Analysis'
NAME_MULTIPLE_PSD = 'Multiple PSD Analysis'

LOGO_APP = './assets/logo_mind_mapper_simple.ico'
