# COLORS
GRAY_COLOR = '#626873'
PINK_GRAY_COLOR = '#E3D5E3'
LIGHT_BLUE_DARK = '#D5E9F0'
BLACK = '#222222'
LIGHT_GRAY_COLOR = '#B7B6B8'
BG_COLOR = '#F0EBEB'  # background color
PINK_COLOR = '#F5C6F5'
BORDER_COLOR = BLACK

# FONTS
FAMILY_FONT = 'roboto'

TYPE_ANALYSIS = ['Select Type of Analysis', 'Data Smoothing', 'PSD Analysis']

# SIZES
WIDTH_LEFT_SIDE = 300
RB_WIDTH = 25
RB_HEIGHT = 25
TITLE_SIZE = 30
SUBTITLE_SIZE = 20
TEXT_SIZE = 12

# EXTRAS
BORDER_WIDTH_FRAME = 2
PADY_INPUTS = 5

# TYPE FILE
LFP = 'LFP'
LFP_INT = 0
SPIKE = 'Spike'
SPIKE_INT = 1

# INPUT TYPE
CHECKBOX = 0
COMBOBOX = 1
RADIOBUTTON = 2
TEXTBOX = 3
ENTRY = 4
